[package]
name = "declarative_enum_dispatch"
version = "0.1.0"
edition = "2021"
authors = ["Zettroke"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
platform_specific = []
[dependencies]
